name: Android CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Release APK (auto debug sign)
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease -x lint -x lintRelease
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: navtex-panel-release.apk
        path: app/build/outputs/apk/release/*.apk
