name: Android CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate Keystore and Sign
      run: |
        keytool -genkeypair -v -keystore release.keystore -alias navtex -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Navtex, OU=Radio, O=Radio, L=Shanghai, ST=Shanghai, C=CN"
    - name: Build Signed APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease -x lint -x lintRelease
        apksigner sign --ks release.keystore --ks-pass pass:123456 --key-pass pass:123456 --out app-release-signed.apk app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: navtex-panel-signed.apk
        path: app-release-signed.apk
